### ISSUE TITLE
mitag download failed

### ISSUE THREAD

**Issue by INFINITY1993** [SushiLab/mTAGs#1]
Hi, 
Thanks for the developing of the taxonomic profiling tool. 
in my case, the mitag download failed several times. Are there other ways to complete this step?
Looking forward for your reply.

**Comment by hjruscheweyh** [comment]
Hi @INFINITY1993 

Thank you for using the mTAGs tool.

mTAGs will download and unzip the database located at ([here](https://sunagawalab.ethz.ch/share/MTAGS_DB/silva/s138/SILVA-138_NR-97_complink_cons.vsearch.udb.gz) and  [here](https://sunagawalab.ethz.ch/share/MTAGS_DB/silva/s138/SILVA-138_NR-97_complink_cons.taxmap.gz)) to the `db` folder which should be located next to the `mtags.py`. You will also need to add an empty marker file to the database folder.

The database folder should look the following after completion:

```
mtags.py
db/
db/SILVA-138_NR-97_complink_cons.vsearch.udb
db/SILVA-138_NR-97_complink_cons.taxmap
db/download.done
__init__.py
data/
data/.....
```

Can you please also share the log from downloading the database via mtags directly?

Best,
Hans
